import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { getServerSession } from 'next-auth';
import Link from 'next/link';
import Logout from './logout';

// Loading the Inter font with a specific subset (Latin in this case)
const inter = Inter({ subsets: ['latin'] });

// Defining metadata for the page, used for SEO or defining document head properties
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

// Defining the RootLayout component that wraps around the application
export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // Retrieving the current server session
  const session = await getServerSession();

  // Returning the layout structure
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav>
          {/* If there is a session, show the Logout component */}
          {!!session && <Logout />}
          {/* If there isn't a session, show a link to the login page */}
          {!session && <Link href="/login">Login</Link>}
        </nav>
        {/* Rendering children components */}
        {children}
      </body>
    </html>
  );
}
